### ISSUE TITLE
[bug] order state not cleared/synced correctly for multiple orders

### ISSUE THREAD

**Issue by robinske** [dkundel/twilio-barista#20]
From the AppSec event - @meganspeir ordered a latte and all subsequent orders for different drinks were still mapped to `latte` (e.g. order #25)

**Comment by dkundel** [comment]
So after the initial order was completed she ordered a different coffee and got the same order?

**Comment by robinske** [comment]
Yep - what she typed would still show up correctly, but "hot chocolate" would map to "latte" still

**Comment by dkundel** [comment]
That's interesting. Would the order number change though?

**Comment by meganspeir** [comment]
Yea the order numbers were correct!

**Comment by dkundel** [comment]
I found the issue with this one :joy: 

In the spellings map there is "late" that matches to "Latte". Since "Hot Chocolate" contains "late" it will map to "Latte" instead of "hot chocolate" :joy:
